/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 19-nov-2019 21:58:03 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `hra_v` CASCADE
;

DROP TABLE IF EXISTS `Podmienky_turnaja` CASCADE
;

DROP TABLE IF EXISTS `rozhoduje_na` CASCADE
;

DROP TABLE IF EXISTS `sa_zucastni` CASCADE
;

DROP TABLE IF EXISTS `Tim` CASCADE
;

DROP TABLE IF EXISTS `Turnaj` CASCADE
;

DROP TABLE IF EXISTS `Uzivatel` CASCADE
;

DROP TABLE IF EXISTS `Zapas` CASCADE
;

/* Create Tables */

CREATE TABLE `hra_v`
(
	`UzivatelID` int NOT NULL,
	`TimID` int NOT NULL
)

;

CREATE TABLE `Podmienky_turnaja`
(
	`Podmienky_turnajaID` int NOT NULL AUTO_INCREMENT,
	`Minimalny_vek_hracov` varchar(100),
	`Pocet_hracov_v_tyme` int,
	`Pocet_tymov` int,
	`Registracny_poplatok` varchar(50),
	CONSTRAINT `PK_Podmienky_turnaja` PRIMARY KEY (`Podmienky_turnajaID` ASC)
)

;

CREATE TABLE `rozhoduje_na`
(
	`UzivatelID` int NOT NULL,
	`ZapasID` int NOT NULL
)

;

CREATE TABLE `sa_zucastni`
(
	`ZapasID` int NOT NULL,
	`TimID` int NOT NULL
)

;

CREATE TABLE `Tim`
(
	`TimID` int NOT NULL AUTO_INCREMENT,
    `Nazov` varchar(100),
	`Logo` varchar(100),
	`Pocet_hracov` int,
	CONSTRAINT `PK_Tim` PRIMARY KEY (`TimID` ASC)
)

;

CREATE TABLE `Turnaj`
(
	`TurnajID` int NOT NULL AUTO_INCREMENT,
    `Nazov` varchar(100),
    `Zaciatok` date,
	`Koniec` date,
	`Vyhra` varchar(50),
	`Sponzori` varchar(100),
	`Podmienky_turnajaID` int NOT NULL,
	`UzivatelID` int NOT NULL,
	CONSTRAINT `PK_Turnaj` PRIMARY KEY (`TurnajID` ASC) 
)

;

CREATE TABLE `Uzivatel`
(
	`UzivatelID` int NOT NULL AUTO_INCREMENT,
    `Meno` varchar(50),
	`Prezvisko` varchar(50),
    `Vek` int,
    `Email` varchar(50),
    `Login` varchar(50),
	`Heslo` varchar(50),
	CONSTRAINT `PK_Uzivatel` PRIMARY KEY (`UzivatelID` ASC)
)

;

CREATE TABLE `Zapas`
(
	`ZapasID` int NOT NULL AUTO_INCREMENT,
	`Nazov` varchar(50) NULL,
    `Miesto` varchar(50) NULL,
    `Datum` date,
	`TurnajID` int NOT NULL,
	CONSTRAINT `PK_Zapas` PRIMARY KEY (`ZapasID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `hra_v` 
 ADD CONSTRAINT `FK_hra_v_Uzivatel`
	FOREIGN KEY (`UzivatelID`) REFERENCES `Uzivatel` (`UzivatelID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `hra_v` 
 ADD CONSTRAINT `FK_hra_v_Tim`
	FOREIGN KEY (`TimID`) REFERENCES `Tim` (`TimID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `rozhoduje_na` 
 ADD CONSTRAINT `FK_rozhoduje_na_Uzivatel`
	FOREIGN KEY (`UzivatelID`) REFERENCES `Uzivatel` (`UzivatelID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `rozhoduje_na` 
 ADD CONSTRAINT `FK_rozhoduje_na_Zapas`
	FOREIGN KEY (`ZapasID`) REFERENCES `Zapas` (`ZapasID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `sa_zucastni` 
 ADD CONSTRAINT `FK_sa_zucastni_Zapas`
	FOREIGN KEY (`ZapasID`) REFERENCES `Zapas` (`ZapasID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `sa_zucastni` 
 ADD CONSTRAINT `FK_sa_zucastni_Tim`
	FOREIGN KEY (`TimID`) REFERENCES `Tim` (`TimID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Turnaj` 
 ADD CONSTRAINT `FK_Turnaj_ma`
	FOREIGN KEY (`Podmienky_turnajaID`) REFERENCES `Podmienky_turnaja` (`Podmienky_turnajaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Turnaj` 
 ADD CONSTRAINT `FK_Turnaj_usporiadava`
	FOREIGN KEY (`UzivatelID`) REFERENCES `Uzivatel` (`UzivatelID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zapas` 
 ADD CONSTRAINT `FK_Zapas_sa_odohra`
	FOREIGN KEY (`TurnajID`) REFERENCES `Turnaj` (`TurnajID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 
;


/* Fill tables */

INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Matej", "Makovčík", 34, "makovcik@gmail.com", "matej1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Tomáš", "Majerský", 42, "majersky@gmail.com", "tomas1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Gejza", "Fico", 25, "fico@gmail.com", "gejza1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Robo", "Tomáš", 16, "tomas@gmail.com", "robo1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Marek", "Horvát", 17, "horvat@gmail.com", "marek1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Jozef", "Kandráč", 18, "kandrac@gmail.com", "jozef1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Nikolas", "Nikolev", 16, "nikolev@gmail.com", "nikolas1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Matej", "Hrdý", 20, "hrdy@gmail.com", "matej2", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Daniel", "Malý", 21, "maly@gmail.com", "daniel1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Ján", "Krátky", 19, "kratky@gmail.com", "jan1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Jaroslav", "Kováč", 18, "kovac@gmail.com", "jaroslav1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Ján", "Matovič", 19, "matovic@gmail.com", "jan2", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Marián", "Hlina", 17, "hlina@gmail.com", "marian1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Juraj", "Kotleta", 17, "kotleta@gmail.com", "juraj1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Ján", "Púčik", 25, "pucik@gmail.com", "jan3", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Andrej", "Zeman", 26, "zeman@gmail.com", "andrej1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Martin", "Danko", 24, "danko@gmail.com", "martin1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Alojz", "Marcin", 22, "marcin@gmail.com", "alojz1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("Igor", "Bugár", 23, "bugar@gmail.com", "igor1", "heslo123");
INSERT INTO `Uzivatel` (`Meno`, `Prezvisko`, `Vek`, `Email`, `Login`, `Heslo`) VALUES ("František", "Novák", 21, "novak@gmail.com", "frantisek1", "heslo123");

INSERT INTO `Podmienky_turnaja` (`Minimalny_vek_hracov`, `Pocet_hracov_v_tyme`, `Pocet_tymov`, `Registracny_poplatok`) VALUES (16, 2, 10, "10 €");
INSERT INTO `Podmienky_turnaja` (`Minimalny_vek_hracov`, `Pocet_hracov_v_tyme`, `Pocet_tymov`, `Registracny_poplatok`) VALUES (20, 1, 10, "1000 €");
INSERT INTO `Podmienky_turnaja` (`Minimalny_vek_hracov`, `Pocet_hracov_v_tyme`, `Pocet_tymov`, `Registracny_poplatok`) VALUES (16, 2, 10, "15 €");
INSERT INTO `Podmienky_turnaja` (`Minimalny_vek_hracov`, `Pocet_hracov_v_tyme`, `Pocet_tymov`, `Registracny_poplatok`) VALUES (16, 1, 10, "50 €");
INSERT INTO `Podmienky_turnaja` (`Minimalny_vek_hracov`, `Pocet_hracov_v_tyme`, `Pocet_tymov`, `Registracny_poplatok`) VALUES (16, 1, 10, "5 €");

INSERT INTO `Turnaj` (`Nazov`, `Zaciatok`, `Koniec`, `Vyhra`, `Sponzori`, `Podmienky_turnajaID`, `UzivatelID`) VALUES ("Okresná liga Trenčín", DATE("2019-06-14"), DATE("2019-08-14"), "125 €", "Mesto Trenčín", 1, 1);
INSERT INTO `Turnaj` (`Nazov`, `Zaciatok`, `Koniec`, `Vyhra`, `Sponzori`, `Podmienky_turnajaID`, `UzivatelID`) VALUES ("Majstrovstvá Slovenska do 20 rokov", DATE("2019-07-20"), DATE("2019-07-30"), "100 000 €", "Mesto Bratislava, SLOVNAFT, ROLEX", 2, 2);
INSERT INTO `Turnaj` (`Nazov`, `Zaciatok`, `Koniec`, `Vyhra`, `Sponzori`, `Podmienky_turnajaID`, `UzivatelID`) VALUES ("Nadačný turnaj HUGO", DATE("2018-09-10"), DATE("2018-09-10"), "0 €", "TV Markíza, TV JOJ, RadioExpress, Kaufland, IBM", 3, 3);
INSERT INTO `Turnaj` (`Nazov`, `Zaciatok`, `Koniec`, `Vyhra`, `Sponzori`, `Podmienky_turnajaID`, `UzivatelID`) VALUES ("Liga ROKE", DATE("2019-05-05"), DATE("2019-09-06"), "2500 €", "SLOVNAFT, IKEA, ESET", 1, 4);
INSERT INTO `Turnaj` (`Nazov`, `Zaciatok`, `Koniec`, `Vyhra`, `Sponzori`, `Podmienky_turnajaID`, `UzivatelID`) VALUES ("Priateľský turnaj", DATE("2018-07-14"), DATE("2019-07-17"), "500 €", "Mesto Košice, Rádio Košice, US Steel", 2, 5);

INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Rýchle šípy", "cesta", 2);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Daemon", "cesta", 2);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Team Liquid", "cesta", 2);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Fnatic", "cesta", 2);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("G2", "cesta", 2);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Adamov", "cesta", 2);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Karči a Lajči", "cesta", 2);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Power Rangers", "cesta", 2);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("FPX", "cesta", 1);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("TSM", "cesta", 1);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Spread Love", "cesta", 1);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Unicorns", "cesta", 1);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Ugly Horses", "cesta", 1);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Small Jack", "cesta", 1);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Pea", "cesta", 1);
INSERT INTO `Tim` (`Nazov`, `Logo`, `Pocet_hracov`) VALUES ("Excalibur", "cesta", 1);

INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (4, 1);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (5, 1);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (6, 2);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (7, 2);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (8, 3);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (9, 3);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (10, 4);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (11, 4);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (12, 5);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (13, 5);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (14, 6);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (15, 6);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (16, 7);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (17, 7);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (18, 8);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (19, 8);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (20, 9);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (4, 10);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (6, 11);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (8, 12);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (10, 13);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (12, 14);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (14, 15);
INSERT INTO `hra_v` (`UzivatelID`, `TimID`) VALUES (16, 16);

INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("Rýchle šípy vs Daemon", "Trenčianska športová hala", DATE("2019-06-14"), 1);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("Team Liquid vs Fnatic", "Trenčianska športová hala", DATE("2019-06-21"), 1);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("G2 vs Adamov", "Trenčianska športová hala", DATE("2019-06-28"), 1);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("Karči a Lajči vs Power Rangers", "Trenčianska športová hala", DATE("2019-07-05"), 1);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("FPX vs TSM", "Bratislava športová hala", DATE("2019-07-20"), 2);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("Spread Love vs Unicorns", "Bratislava športová hala", DATE("2019-07-20"), 2);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("Ugly Horses vs Small Jack", "Bratislava športová hala", DATE("2019-07-21"), 2);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("Pea vs Excalibur", "Bratislava športová hala", DATE("2019-07-21"), 2);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("Rýchle šípy vs Adamov", "Hala radosť v Košiciach", DATE("2019-09-10"), 3);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("G2 vs Fnatic", "Hala radosť v Košiciach", DATE("2019-09-10"), 3);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("FPX vs Unicorns", "SLOVNAFT hala BA", DATE("2019-05-5"), 4);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("TSM vs Spread Love", "SLOVNAFT hala BA", DATE("2019-05-12"), 4);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("Unicorns vs TSM", "SLOVNAFT hala BA", DATE("2019-07-14"), 5);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("Ugly Horses vs FPX", "SLOVNAFT hala BA", DATE("2019-07-14"), 5);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("Small Jack vs Spread Love", "SLOVNAFT hala BA", DATE("2019-07-15"), 5);
INSERT INTO `Zapas` (`Nazov`, `Miesto`, `Datum`, `TurnajID`) VALUES ("Pea vs Excalibur", "SLOVNAFT hala BA", DATE("2019-07-15"), 5);

INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (1, 1, 2);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (2, 3, 4);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (3, 5, 6);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (4, 7, 8);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (5, 9, 10);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (6, 11, 12);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (7, 13, 14);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (8, 15, 16);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (9, 1, 6);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (10, 5, 4);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (11, 9, 12);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (12, 10, 11);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (13, 12, 10);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (14, 13, 9);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (15, 14, 11);
INSERT INTO `sa_zucastni` (`ZapasID`, `TimID`, `TimID`) VALUES (16, 15, 16);
/*
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (2, 1);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (2, 2);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (2, 3);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (2, 4);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (1, 5);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (3, 6);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (3, 7);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (1, 8s);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (2, 9);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (1, 10);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (3, 11);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (3, 12);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (1, 13);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (3, 14);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (3, 15);
INSERT INTO `rozhoduje_na` (`UzivatelID`, `ZapasID`) VALUES (1, 16);
*/